export const FETCH_LABEL_SUCCESS = 'FETCH_LABEL_SUCCESS';
export const ADD_LABEL_SUCCESS = 'ADD_LABEL_SUCCESS';
export const MODIFY_LABEL_SUCCESS = 'MODIFY_LABEL_SUCCESS';
export const DELETE_LABEL_SUCCESS = 'DELETE_LABEL_SUCCESS';