export const FETCH_PROJECT_SUCCESS = 'FETCH_PROJECT_SUCCESS';
export const ADD_PROJECT_SUCCESS = 'ADD_PROJECT_SUCCESS';
export const MODIFY_PROJECT_SUCCESS = 'MODIFY_PROJECT_SUCCESS';
export const DELETE_PROJECT_SUCCESS = 'DELETE_PROJECT_SUCCESS';