export const FETCH_COMMENT_SUCCESS = 'FETCH_COMMENT_SUCCESS';
export const ADD_COMMENT_SUCCESS = 'ADD_COMMENT_SUCCESS';
export const DELETE_COMMENT_SUCCESS = 'DELETE_COMMENT_SUCCESS';
export const FETCH_POST_SUCCESS = 'FETCH_POST_SUCCESS';